// transaction
export const RESET_TRANSACTION_DATA = 'transaction/RESET_TRANSACTION_DATA';
export const SET_TRANSACTION_PAGE_STEP = 'transaction/SET_TRANSACTION_PAGE_STEP';
export const SAVE_CREATE_TRANSACTION_FORM = 'transaction/SAVE_CREATE_TRANSACTION_FORM';
export const RESET_TRANSACTION_PAGE_STEP = 'transaction/RESET_TRANSACTION_PAGE_STEP';
export const SET_TRANSACTION_FEE = 'transaction/SET_TRANSACTION_FEE';
export const RESET_TRANSACTION_FEE = 'transaction/RESET_TRANSACTION_FEE';
export const SAVE_TRANSACTION_SUCCEEDED_DATA = 'transaction/SAVE_TRANSACTION_SUCCEEDED_DATA';
export const SAVE_TRANSACTION_DETAILS_DATA = 'transaction/SAVE_TRANSACTION_DETAILS_DATA';
export const SAVE_TRANSACTION_FULL_DETAILS_DATA = 'transaction/SAVE_TRANSACTION_FULL_DETAILS_DATA';
export const ADD_API_CONSOLE_OUTPUT_DATA = 'transaction/ADD_API_CONSOLE_OUTPUT_DATA';
export const RESET_API_CONSOLE_OUTPUT = 'transaction/RESET_API_CONSOLE_OUTPUT';
export const SAVE_SUBSCRIBE_DATA = 'transaction/SAVE_SUBSCRIBE_DATA';
export const REMOVE_API_CONSOLE_OUTPUT_DATA_PART = 'transaction/REMOVE_API_CONSOLE_OUTPUT_DATA_PART';
export const MOVE_TO_AUDIT = 'transaction/MOVE_TO_AUDIT';
export const SAVE_SIGNED_KEY = 'transaction/SAVE_SIGNED_KEY';
export const UPDATE_STATUSES = 'transaction/UPDATE_STATUSES';

export const SET_CHANGES_STATE = 'main/SET_CHANGES_STATE';
export const SAVE_PREVIOUS_STEP = 'main/SAVE_PREVIOUS_STEP';

// subscriptions
export const SAVE_SUBSCRIPTION_LIST = 'subscriptions/SAVE_SUBSCRIPTION_LIST';
export const ADD_DETAILS_SUBSCRIPTION_LIST = 'subscriptions/ADD_DETAILS_SUBSCRIPTION_LIST';
export const UPDATE_STATUSES_SUBSCRIPTION = 'subscriptions/UPDATE_STATUSES';
export const UPDATE_SUBSCRIPTION = 'subscriptions/UPDATE_SUBSCRIPTION';
export const REMOVE_FROM_UPDATED_SUBSCRIPTIONS = 'subscriptions/REMOVE_FROM_UPDATED_SUBSCRIPTIONS';
export const RESET_SUBSCRIPTIONS = 'subscriptions/RESET_SUBSCRIPTIONS';
